title: Gymnastiar Al Khoarizmy # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>I am an undergraduate student in Data Science at Institut Teknologi Sumatera (ITERA), passionate about uncovering insights from data and solving complex problems. My academic journey has equipped me with robust skills in data science and data analytics, enabling me to transform raw data into meaningful information.</p>
    
    <h2>Technical Skills</h2>
    <ul>
        <li><strong>Programming Languages:</strong> Proficient in Python and R, utilizing these tools for statistical analysis, data visualization, machine learning, and more.</li>
        <li><strong>Database Management:</strong> Experienced in MySQL for efficient data querying and management, ensuring smooth and accurate data handling.</li>
        <li><strong>Analytical Tools:</strong> Adept at using various libraries and frameworks to analyze and interpret data, delivering actionable insights.</li>
    </ul>
    
    <h2>Interests and Projects</h2>
    <p>Throughout my studies, I have undertaken several projects that highlight my ability to apply theoretical knowledge to practical scenarios. From predictive modeling to data visualization, I thrive on the challenges presented by real-world data.</p>
    <p>I am eager to continue growing in the field of data science, constantly learning and adapting to new technologies and methodologies. My goal is to leverage data to drive informed decision-making and innovation.</p>
    
  <br><br>
  <a href="https://www.linkedin.com/in/gymnastiar-al-khoarizmy-0b437b1b5/">View my LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
